controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    forward_effort_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    pid_position_controller:
      type: position_controllers/JointGroupPositionController
      

forward_position_controller:
  ros__parameters:
    joints:
      - coxa_joint_F1
      - merus_joint_F1
      - carpus_joint_F1
      - manus_joint_F1
      - coxa_joint_F2
      - merus_joint_F2
      - carpus_joint_F2
      - manus_joint_F2
      - coxa_joint_L1
      - merus_joint_L1
      - carpus_joint_L1
      - manus_joint_L1
      - coxa_joint_L2
      - merus_joint_L2
      - carpus_joint_L2
      - manus_joint_L2
      - coxa_joint_L3
      - merus_joint_L3
      - carpus_joint_L3
      - manus_joint_L3
      - coxa_joint_L4
      - merus_joint_L4
      - carpus_joint_L4
      - manus_joint_L4
      - coxa_joint_R1
      - merus_joint_R1
      - carpus_joint_R1
      - manus_joint_R1
      - coxa_joint_R2
      - merus_joint_R2
      - carpus_joint_R2
      - manus_joint_R2
      - coxa_joint_R3
      - merus_joint_R3
      - carpus_joint_R3
      - manus_joint_R3
      - coxa_joint_R4
      - merus_joint_R4
      - carpus_joint_R4
      - manus_joint_R4


    interface_name: position

forward_velocity_controller:
  ros__parameters:
    joints:
      - coxa_joint_F1
      - merus_joint_F1
      - carpus_joint_F1
      - manus_joint_F1
      - coxa_joint_F2
      - merus_joint_F2
      - carpus_joint_F2
      - manus_joint_F2
      - coxa_joint_L1
      - merus_joint_L1
      - carpus_joint_L1
      - manus_joint_L1
      - coxa_joint_L2
      - merus_joint_L2
      - carpus_joint_L2
      - manus_joint_L2
      - coxa_joint_L3
      - merus_joint_L3
      - carpus_joint_L3
      - manus_joint_L3
      - coxa_joint_L4
      - merus_joint_L4
      - carpus_joint_L4
      - manus_joint_L4
      - coxa_joint_R1
      - merus_joint_R1
      - carpus_joint_R1
      - manus_joint_R1
      - coxa_joint_R2
      - merus_joint_R2
      - carpus_joint_R2
      - manus_joint_R2
      - coxa_joint_R3
      - merus_joint_R3
      - carpus_joint_R3
      - manus_joint_R3
      - coxa_joint_R4
      - merus_joint_R4
      - carpus_joint_R4
      - manus_joint_R4


    interface_name: velocity

forward_effort_controller:
  ros__parameters:
    joints:
      - coxa_joint_F1
      - merus_joint_F1
      - carpus_joint_F1
      - manus_joint_F1
      - coxa_joint_F2
      - merus_joint_F2
      - carpus_joint_F2
      - manus_joint_F2
      - coxa_joint_L1
      - merus_joint_L1
      - carpus_joint_L1
      - manus_joint_L1
      - coxa_joint_L2
      - merus_joint_L2
      - carpus_joint_L2
      - manus_joint_L2
      - coxa_joint_L3
      - merus_joint_L3
      - carpus_joint_L3
      - manus_joint_L3
      - coxa_joint_L4
      - merus_joint_L4
      - carpus_joint_L4
      - manus_joint_L4
      - coxa_joint_R1
      - merus_joint_R1
      - carpus_joint_R1
      - manus_joint_R1
      - coxa_joint_R2
      - merus_joint_R2
      - carpus_joint_R2
      - manus_joint_R2
      - coxa_joint_R3
      - merus_joint_R3
      - carpus_joint_R3
      - manus_joint_R3
      - coxa_joint_R4
      - merus_joint_R4
      - carpus_joint_R4
      - manus_joint_R4


    interface_name: effort     

joint_trajectory_position_controller:
  ros__parameters:
    joints:
      - coxa_joint_F1
      - merus_joint_F1
      - carpus_joint_F1
      - manus_joint_F1
      - coxa_joint_F2
      - merus_joint_F2
      - carpus_joint_F2
      - manus_joint_F2
      - coxa_joint_L1
      - merus_joint_L1
      - carpus_joint_L1
      - manus_joint_L1
      - coxa_joint_L2
      - merus_joint_L2
      - carpus_joint_L2
      - manus_joint_L2
      - coxa_joint_L3
      - merus_joint_L3
      - carpus_joint_L3
      - manus_joint_L3
      - coxa_joint_L4
      - merus_joint_L4
      - carpus_joint_L4
      - manus_joint_L4
      - coxa_joint_R1
      - merus_joint_R1
      - carpus_joint_R1
      - manus_joint_R1
      - coxa_joint_R2
      - merus_joint_R2
      - carpus_joint_R2
      - manus_joint_R2
      - coxa_joint_R3
      - merus_joint_R3
      - carpus_joint_R3
      - manus_joint_R3
      - coxa_joint_R4
      - merus_joint_R4
      - carpus_joint_R4
      - manus_joint_R4

    command_interfaces:
      - position

    state_interfaces:
      - position
      #- velocity
      #- effort

pid_position_controller:
  ros__parameters:
    joints:
      - coxa_joint_F1
      - merus_joint_F1
      - carpus_joint_F1
      - manus_joint_F1
      - coxa_joint_F2
      - merus_joint_F2
      - carpus_joint_F2
      - manus_joint_F2
      - coxa_joint_L1
      - merus_joint_L1
      - carpus_joint_L1
      - manus_joint_L1
      - coxa_joint_L2
      - merus_joint_L2
      - carpus_joint_L2
      - manus_joint_L2
      - coxa_joint_L3
      - merus_joint_L3
      - carpus_joint_L3
      - manus_joint_L3
      - coxa_joint_L4
      - merus_joint_L4
      - carpus_joint_L4
      - manus_joint_L4
      - coxa_joint_R1
      - merus_joint_R1
      - carpus_joint_R1
      - manus_joint_R1
      - coxa_joint_R2
      - merus_joint_R2
      - carpus_joint_R2
      - manus_joint_R2
      - coxa_joint_R3
      - merus_joint_R3
      - carpus_joint_R3
      - manus_joint_R3
      - coxa_joint_R4
      - merus_joint_R4
      - carpus_joint_R4
      - manus_joint_R4


    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)